name: Deploy to HakuLess.github.io

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Clear cache
        run: rm -rf docs/.vuepress/dist
      
      - name: Build docs
        run: npm run docs:build
      
      - name: Check target repository
        run: |
          echo "Checking access to HakuLess/HakuLess.github.io..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/HakuLess/HakuLess.github.io
      
      - name: Deploy to HakuLess.github.io
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vuepress/dist/
          branch: master
          repository-name: HakuLess/HakuLess.github.io
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: GitHub Actions
          git-config-email: actions@github.com
          force: true
